#!/bin/bash

set -e

# there's rate limiting on the server logins, so we need sleeps
DELAY=3

printf "Creating directory structure..."
ssh s4320859-csse1001.zones.eait.uq.edu.au <<ENDSSH
cd /opt/local/share/MyPyTutor/MPT3_CSSE1001
mkdir -p data/answers
mkdir -p data/submissions
mkdir -p data/feedback
ENDSSH
printf "done\n"

sleep $DELAY

printf "Uploading hash files..."
rsync -avz tutorial_* s4320859-csse1001.zones.eait.uq.edu.au:/opt/local/share/MyPyTutor/MPT3_CSSE1001/data/submissions
printf "done\n"
